import FWCore.ParameterSet.Config as cms

ggee = cms.EDAnalyzer(
    'GammaGammaEE',
    GlobalEleCollectionLabel = cms.untracked.InputTag("selectedPatElectrons"),
    #GlobalEleCollectionLabel = cms.untracked.InputTag("goodElectrons"),
    electronsGsf = cms.InputTag("gedGsfElectrons"),
    #eleLooseIdMap = cms.InputTag("egmGsfElectronIDs:cutBasedElectronID_Spring15_25ns_V1_standalone_loose"),
    #eleMediumIdMap = cms.InputTag("egmGsfElectronIDs:cutBasedElectronID_Spring15_25ns_V1_standalone_medium"),
    #eleTightIdMap = cms.InputTag("egmGsfElectronIDs:cutBasedElectronID_Spring15_25ns_V1_standalone_tight"),
    eleLooseIdMap = cms.InputTag("egmGsfElectronIDs:cutBasedElectronID-Spring15-25ns-V1-standalone-loose"),
    eleMediumIdMap = cms.InputTag("egmGsfElectronIDs:cutBasedElectronID-Spring15-25ns-V1-standalone-medium"),
    eleTightIdMap = cms.InputTag("egmGsfElectronIDs:cutBasedElectronID-Spring15-25ns-V1-standalone-tight"),
    #eleLooseIdMap = cms.InputTag("egmGsfElectronIDs:mvaEleID-Spring15-25ns-Trig-V1-wp90"),
    #eleMediumIdMap = cms.InputTag("egmGsfElectronIDs:mvaEleID-Spring15-25ns-Trig-V1-wp90"),
    #eleTightIdMap = cms.InputTag("egmGsfElectronIDs:mvaEleID-Spring15-25ns-Trig-V1-wp80"),
    #eleLooseIdMap = cms.InputTag("egmGsfElectronIDs:cutBasedElectronID-Summer16-80X-V1-loose"),
    #eleMediumIdMap = cms.InputTag("egmGsfElectronIDs:cutBasedElectronID-Summer16-80X-V1-medium"),
    #eleTightIdMap = cms.InputTag("egmGsfElectronIDs:cutBasedElectronID-Summer16-80X-V1-tight"),
    SqrtS = cms.double(13000.),
    HLTMenuLabel = cms.string("HLT"),
    LeptonsType = cms.InputTag('electrons'),
    RunOnMC = cms.untracked.bool(False),
    RunOnProtons = cms.untracked.bool(True),
    MCAcceptPtCut = cms.untracked.double(0.),
    MCAcceptEtaCut = cms.untracked.double(-1.),
    GenParticlesCollectionLabel = cms.InputTag('genParticles'),
    PrintCandidates = cms.untracked.bool(False),
)
